#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""program"""
__author__ = "JamongSS"
__date__ = "2025-09-23"
__last_modified_by__ = "JamongSS"
__last_modified_date__ = "0000-00-00"
__maintainer__ = "JamongSS"

###########
# imports #
###########
import os
import sys
import traceback
import configparser
import supervisor.supervisorctl


#########
# class #
#########
class Svctl(object):
    def __init__(self):
        try:
            self.engn_root = os.path.dirname(os.path.abspath(__file__))
            self.re_conf_path = os.path.join(
                self.engn_root, 'cfg', 'replace_supervisord.conf')

            self.config = configparser.RawConfigParser()
            self.config.read(self.re_conf_path)
        except Exception:
            print(traceback.format_exc())
            sys.exit(1)

    def run(self):
        try:
            # args = ['-c', self.re_conf_path, '-u', 'user', '-p', 'passowrd']
            args = ['-c', self.re_conf_path]
            args.extend(sys.argv[1:])

            sys.exit(supervisor.supervisorctl.main(args))
        except Exception:
            print(traceback.format_exc())
            sys.exit(1)


########
# main #
########
if __name__ == '__main__':
    svctl = Svctl()
    svctl.run()

